import fs from 'node:fs/promises'
import {existsSync,chmodSync} from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {execFile,spawn} from 'node:child_process'

/**
 * Run installed packages as long-lived services instead of terminal children:
 * systemd user units on Linux, LaunchAgents on macOS, logon tasks on Windows,
 * with a detached-process fallback. Services restart on failure and (with a
 * user manager / linger) start on boot. Only `0kay-pm stop <package>` stops them.
 */

/** POSIX single-quote escaping for a shell word. */
export function shellQuote(value){
 return `'${String(value).replace(/'/g,"'\\''")}'`
}
/** Quote a Windows command argument for a .cmd wrapper. */
export function cmdQuote(value){
 return `"${String(value).replace(/"/g,'""').replace(/%/g,'%%')}"`
}
function serviceRoot(home){return path.join(home,'services')}
function logRoot(home){return path.join(home,'logs')}
function systemdDir(){return path.join(process.env.XDG_CONFIG_HOME||path.join(os.homedir(),'.config'),'systemd','user')}
function launchdDir(){return path.join(os.homedir(),'Library','LaunchAgents')}

export function renderPosixWrapper(unit,home){
 const extra=(unit.binDirs||[]).join(':')
 const pathValue=[extra,process.env.PATH||'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'].filter(Boolean).join(':')
 const lines=['#!/bin/sh','# Generated by 0kay-pm. Do not edit.',`export PATH=${shellQuote(pathValue)}`]
 for(const [key,value] of Object.entries(unit.env||{}))lines.push(`export ${key}=${shellQuote(value)}`)
 lines.push(`cd ${shellQuote(unit.cwd)} || exit 1`)
 lines.push(`exec ${unit.command.map(shellQuote).join(' ')}`)
 return lines.join('\n')+'\n'
}
export function renderWindowsWrapper(unit,home){
 const extra=(unit.binDirs||[]).join(';')
 const lines=['@echo off','rem Generated by 0kay-pm. Do not edit.',`set "PATH=${extra};%PATH%"`]
 for(const [key,value] of Object.entries(unit.env||{}))lines.push(`set "${key}=${String(value).replace(/%/g,'%%')}"`)
 lines.push(`cd /d "${unit.cwd}" || exit /b 1`)
 lines.push(unit.command.map(cmdQuote).join(' '))
 return lines.join('\r\n')+'\r\n'
}
/** systemd unit paths: escape % and spaces (WorkingDirectory= must be unquoted). */
function systemdPath(value){
 return String(value).replace(/%/g,'%%').replace(/ /g,'\\x20')
}
export function renderSystemdUnit(unit,wrapper){
 return [
  '[Unit]',
  `Description=0kay-pm: ${unit.name}`,
  'After=network-online.target',
  'Wants=network-online.target',
  '',
  '[Service]',
  'Type=simple',
  `ExecStart=/bin/sh "${systemdPath(wrapper)}"`,
  `WorkingDirectory=${systemdPath(unit.cwd)}`,
  'Restart=always',
  'RestartSec=3',
  'KillMode=mixed',
  '',
  '[Install]',
  'WantedBy=default.target',
  '',
 ].join('\n')
}
export function renderLaunchdPlist(unit,wrapper,logPath){
 const esc=(value)=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
 return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>Label</key><string>com.0kay.${esc(unit.name)}</string>
<key>ProgramArguments</key><array><string>/bin/sh</string><string>${esc(wrapper)}</string></array>
<key>RunAtLoad</key><true/>
<key>KeepAlive</key><true/>
<key>StandardOutPath</key><string>${esc(logPath)}</string>
<key>StandardErrorPath</key><string>${esc(logPath)}</string>
</dict></plist>
`
}
function run(file,args,{ignore=false}={}){
 return new Promise(resolve=>{
  execFile(file,args,{windowsHide:true},(error,stdout,stderr)=>{
   if(error&&!ignore)resolve({ok:false,error:`${file}: ${stderr||error.message}`.trim()})
   else resolve({ok:true,stdout:String(stdout||'').trim(),stderr:String(stderr||'').trim()})
  })
 })
}
/** Write wrappers for each unit and return them with wrapper/log paths. */
async function materialize(units,ctx){
 const root=serviceRoot(ctx.home);await fs.mkdir(root,{recursive:true});await fs.mkdir(logRoot(ctx.home),{recursive:true})
 const prepared=[]
 for(const unit of units){
  const ext=process.platform==='win32'?'cmd':'sh'
  const wrapper=path.join(root,`${unit.name}.${ext}`)
  const content=process.platform==='win32'?renderWindowsWrapper(unit,ctx.home):renderPosixWrapper(unit,ctx.home)
  await fs.writeFile(wrapper,content,{mode:0o755})
  try{chmodSync(wrapper,0o755)}catch{}
  prepared.push({...unit,wrapper,log:path.join(logRoot(ctx.home),`${unit.name}.log`)})
 }
 return prepared
}
async function ensureLinger(ctx){
 if(process.getuid&&process.getuid()===0)return
 const user=os.userInfo().username
 const show=await run('loginctl',['show-user',user,'-p','Linger'],{ignore:true})
 if(/Linger=yes/.test(show.stdout||''))return
 const enabled=await run('loginctl',['enable-linger',user],{ignore:true})
 if(!enabled.ok)ctx.log(`Could not enable linger; services start on login until you run: sudo loginctl enable-linger ${user}`)
}
async function installSystemd(units,ctx){
 const probe=await run('systemctl',['--user','show-environment'])
 if(!probe.ok)return {ok:false,error:probe.error||'systemctl --user unavailable'}
 const dir=systemdDir();await fs.mkdir(dir,{recursive:true})
 const prepared=await materialize(units,ctx)
 for(const unit of prepared)await fs.writeFile(path.join(dir,`${unit.name}.service`),renderSystemdUnit(unit,unit.wrapper))
 const reload=await run('systemctl',['--user','daemon-reload'])
 if(!reload.ok)return {ok:false,error:reload.error}
 for(const unit of prepared){
  const enabled=await run('systemctl',['--user','enable','--now',`${unit.name}.service`])
  if(!enabled.ok){
   // Undo the units enabled so far so the detached fallback has no duplicates.
   for(const done of prepared)await run('systemctl',['--user','disable','--now',`${done.name}.service`],{ignore:true})
   return {ok:false,error:enabled.error}
  }
 }
 await ensureLinger(ctx)
 return {ok:true}
}
async function installLaunchd(units,ctx){
 const prepared=await materialize(units,ctx);const dir=launchdDir();await fs.mkdir(dir,{recursive:true})
 const domain=`gui/${process.getuid()}`
 for(const unit of prepared){
  const plist=path.join(dir,`com.0kay.${unit.name}.plist`)
  await fs.writeFile(plist,renderLaunchdPlist(unit,unit.wrapper,unit.log))
  await run('launchctl',['bootout',domain,plist],{ignore:true})
  const loaded=await run('launchctl',['bootstrap',domain,plist],{ignore:true})
  if(!loaded.ok)await run('launchctl',['load','-w',plist],{ignore:true})
 }
}
async function installWindows(units,ctx){
 const prepared=await materialize(units,ctx)
 for(const unit of prepared){
  const task=`0kay-pm\\${unit.name}`
  await run('schtasks',['/Create','/F','/TN',task,'/TR',`"${unit.wrapper}"`,'/SC','ONLOGON'])
  await run('schtasks',['/Run','/TN',task],{ignore:true})
 }
}
async function installDetached(units,ctx){
 const prepared=await materialize(units,ctx)
 for(const unit of prepared){
  const handle=await fs.open(unit.log,'a')
  try{
   const shell=process.platform==='win32'?'cmd.exe':(existsSync('/bin/sh')?'/bin/sh':'sh')
   const args=process.platform==='win32'?['/c',unit.wrapper]:[unit.wrapper]
   const child=spawn(shell,args,{detached:true,stdio:['ignore',handle.fd,handle.fd]})
   child.unref()
   await fs.writeFile(path.join(serviceRoot(ctx.home),`${unit.name}.pid`),String(child.pid))
  }finally{await handle.close()}
 }
}
async function stopDetached(home,name){
 const pidFile=path.join(serviceRoot(home),`${name}.pid`)
 const pid=Number(await fs.readFile(pidFile,'utf8').catch(()=>''))
 if(pid){try{process.kill(-pid,'SIGTERM')}catch{try{process.kill(pid,'SIGTERM')}catch{}}}
 await fs.rm(pidFile,{force:true})
}
/** Install + start all units, choosing the best backend for this platform. */
export async function installServices({home,units,log=console.log}){
 if(!units.length)return {backend:'none'}
 const ctx={home,log}
 if(process.platform==='linux'){
  const result=await installSystemd(units,ctx)
  if(result.ok)return {backend:'systemd'}
  log(`systemd --user unavailable (${result.error}); using detached processes instead.`)
  await installDetached(units,ctx)
  return {backend:'detached'}
 }
 if(process.platform==='darwin'){await installLaunchd(units,ctx);return {backend:'launchd'}}
 if(process.platform==='win32'){await installWindows(units,ctx);return {backend:'schtasks'}}
 await installDetached(units,ctx)
 return {backend:'detached'}
}
/** Stop + disable the given service names and remove their units. */
export async function stopServices({home,names,log=console.log}){
 for(const name of names){
  if(process.platform==='linux')await run('systemctl',['--user','disable','--now',`${name}.service`],{ignore:true})
  else if(process.platform==='darwin'){
   const plist=path.join(launchdDir(),`com.0kay.${name}.plist`)
   await run('launchctl',['bootout',`gui/${process.getuid()}`,plist],{ignore:true})
   await fs.rm(plist,{force:true})
  } else if(process.platform==='win32'){
   await run('schtasks',['/End','/TN',`0kay-pm\\${name}`],{ignore:true})
   await run('schtasks',['/Delete','/TN',`0kay-pm\\${name}`,'/F'],{ignore:true})
  }
  await fs.rm(path.join(home,'services',`${name}.sh`),{force:true})
  await fs.rm(path.join(home,'services',`${name}.cmd`),{force:true})
  await stopDetached(home,name)
 }
 if(process.platform==='linux')await run('systemctl',['--user','daemon-reload'],{ignore:true})
}
/** Report the backend state for each service name. */
export async function servicesStatus({home,names}){
 const rows=[]
 for(const name of names){
  let state='unknown'
  if(process.platform==='linux'){
   const result=await run('systemctl',['--user','is-active',`${name}.service`],{ignore:true})
   state=result.stdout||'inactive'
  } else if(process.platform==='darwin'){
   const result=await run('launchctl',['print',`gui/${process.getuid()}/com.0kay.${name}`],{ignore:true})
   state=result.ok?'running':'stopped'
  } else if(process.platform==='win32'){
   const result=await run('schtasks',['/Query','/TN',`0kay-pm\\${name}`],{ignore:true})
   state=result.ok?'registered':'missing'
  } else {
   const pid=Number(await fs.readFile(path.join(home,'services',`${name}.pid`),'utf8').catch(()=>''))
   state=pid?'running':'stopped'
  }
  rows.push({name,state})
 }
 return rows
}
